---
apiVersion: v1
kind: Service

metadata:
  name: fb-lb-service
  labels:
    app: facebook

spec :
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
      app: facebook
      tier: frontend

    
  
